name: CI usando workflow reutilizable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
   # uses: virtualitosorg/-org-reusable-workflows/.github/workflows/net-ci.yml@main
    uses: grodriguez-it/calculadora-cf/.github/workflows/reusable.yml@main
    with:
      project-path: calculadora.csproj
      run-app: "false"
